/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ContattoController;
import Model.Contatto;
import Model.Model;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.security.auth.callback.ConfirmationCallback;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author itzpa
 */
public class contattoFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel;
    ContattoController controller;
    private Model model = new Model();

    /**
     * Creates new form MainFrm
     */
    public contattoFrame() {
        // Inizializza i componenti grafici
        initComponents();

        // Ora che i componenti sono inizializzati, puoi creare il controller
        controller = new ContattoController(this, model);
        if(model.size() == 0){
            contattiPresLbl.setText("Non è presente nessun contatto ");
        } else {
            contattiPresLbl.setText("Contatti presenti nella rubrica: " + model.size()+" ");
        }
        

        // Imposta l'icona della finestra
        setIconImage(new ImageIcon(getClass().getResource("/photo/contact.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainModificaPanel = new javax.swing.JPanel();
        modificaPanel = new javax.swing.JPanel();
        titoloLbl = new javax.swing.JLabel();
        datiPanel = new javax.swing.JPanel();
        nomeLbl = new javax.swing.JLabel();
        nomeTxt = new javax.swing.JTextField();
        cognomeLbl = new javax.swing.JLabel();
        cognomeTxt = new javax.swing.JTextField();
        telefonoLbl = new javax.swing.JLabel();
        telefonoTxt = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        btnPanel = new javax.swing.JPanel();
        eliminaBtn = new javax.swing.JButton();
        modificaBtn = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        rubricaTbl = new javax.swing.JTable();
        contattiPresLbl = new javax.swing.JLabel();
        ricercaBtnPanel = new javax.swing.JPanel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        salvaFastBtn = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        addContattoFastBtn = new javax.swing.JButton();
        cercaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cercaTxt = new javax.swing.JTextField();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        salvaItem = new javax.swing.JMenuItem();
        contattoMenu = new javax.swing.JMenu();
        aggiungiContatto = new javax.swing.JMenuItem();
        temiMenu = new javax.swing.JMenu();
        chiaroItem = new javax.swing.JMenuItem();
        scuroItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rubrica GUI");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setName("contattoFrame"); // NOI18N

        mainModificaPanel.setPreferredSize(new java.awt.Dimension(240, 353));
        mainModificaPanel.setLayout(new java.awt.BorderLayout());

        titoloLbl.setBackground(new java.awt.Color(169, 222, 249));
        titoloLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titoloLbl.setForeground(java.awt.Color.black);
        titoloLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titoloLbl.setText("Rubrica GUI - BETA");
        titoloLbl.setOpaque(true);

        datiPanel.setLayout(new java.awt.GridLayout(8, 0));

        nomeLbl.setText("Nome");
        datiPanel.add(nomeLbl);

        nomeTxt.setText("Nome");
        nomeTxt.setEnabled(false);
        nomeTxt.setPreferredSize(new java.awt.Dimension(71, 12));
        datiPanel.add(nomeTxt);

        cognomeLbl.setText("Cognome");
        datiPanel.add(cognomeLbl);

        cognomeTxt.setText("Cognome");
        cognomeTxt.setEnabled(false);
        datiPanel.add(cognomeTxt);

        telefonoLbl.setText("Telefono");
        datiPanel.add(telefonoLbl);

        telefonoTxt.setText("Telefono");
        telefonoTxt.setEnabled(false);
        datiPanel.add(telefonoTxt);

        emailLbl.setText("Email");
        datiPanel.add(emailLbl);

        emailTxt.setText("Email");
        emailTxt.setEnabled(false);
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        datiPanel.add(emailTxt);

        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        eliminaBtn.setBackground(new java.awt.Color(213, 45, 45));
        eliminaBtn.setForeground(new java.awt.Color(255, 255, 255));
        eliminaBtn.setText("Elimina");
        eliminaBtn.setEnabled(false);
        eliminaBtn.setOpaque(true);
        eliminaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaBtnActionPerformed(evt);
            }
        });
        btnPanel.add(eliminaBtn);

        modificaBtn.setText("Modifica");
        modificaBtn.setEnabled(false);
        modificaBtn.setPreferredSize(new java.awt.Dimension(103, 23));
        modificaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaBtnActionPerformed(evt);
            }
        });
        btnPanel.add(modificaBtn);

        javax.swing.GroupLayout modificaPanelLayout = new javax.swing.GroupLayout(modificaPanel);
        modificaPanel.setLayout(modificaPanelLayout);
        modificaPanelLayout.setHorizontalGroup(
            modificaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titoloLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(modificaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(datiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(btnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );
        modificaPanelLayout.setVerticalGroup(
            modificaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modificaPanelLayout.createSequentialGroup()
                .addComponent(titoloLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(datiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(btnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        mainModificaPanel.add(modificaPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainModificaPanel, java.awt.BorderLayout.LINE_START);

        tablePanel.setLayout(new java.awt.BorderLayout());

        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        rubricaTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cognome", "Telefono", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rubricaTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rubricaTblMouseClicked(evt);
            }
        });
        scrollPane.setViewportView(rubricaTbl);

        tablePanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        contattiPresLbl.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        contattiPresLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tablePanel.add(contattiPresLbl, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(tablePanel, java.awt.BorderLayout.CENTER);

        ricercaBtnPanel.setPreferredSize(new java.awt.Dimension(834, 30));
        ricercaBtnPanel.setLayout(new javax.swing.BoxLayout(ricercaBtnPanel, javax.swing.BoxLayout.X_AXIS));
        ricercaBtnPanel.add(filler2);

        salvaFastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/save_1.png"))); // NOI18N
        salvaFastBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        salvaFastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaFastBtnActionPerformed(evt);
            }
        });
        ricercaBtnPanel.add(salvaFastBtn);
        ricercaBtnPanel.add(filler1);

        addContattoFastBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/person.png"))); // NOI18N
        addContattoFastBtn.setPreferredSize(new java.awt.Dimension(30, 30));
        addContattoFastBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContattoFastBtnActionPerformed(evt);
            }
        });
        ricercaBtnPanel.add(addContattoFastBtn);

        cercaPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/search.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(22, 22));
        cercaPanel.add(jLabel1);

        cercaTxt.setText("Cerca...");
        cercaTxt.setToolTipText("");
        cercaTxt.setPreferredSize(new java.awt.Dimension(200, 20));
        cercaTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cercaTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cercaTxtFocusLost(evt);
            }
        });
        cercaTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cercaTxtKeyReleased(evt);
            }
        });
        cercaPanel.add(cercaTxt);

        ricercaBtnPanel.add(cercaPanel);

        getContentPane().add(ricercaBtnPanel, java.awt.BorderLayout.PAGE_START);

        fileMenu.setText("File");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/newFile20.png"))); // NOI18N
        jMenuItem2.setText("Nuova Rubrica");
        jMenuItem2.setEnabled(false);
        fileMenu.add(jMenuItem2);

        salvaItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        salvaItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/save_1.png"))); // NOI18N
        salvaItem.setText("Salva Rubrica");
        salvaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaItemActionPerformed(evt);
            }
        });
        fileMenu.add(salvaItem);

        menuBar.add(fileMenu);

        contattoMenu.setText("Contatto");

        aggiungiContatto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_PLUS, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aggiungiContatto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photo/person.png"))); // NOI18N
        aggiungiContatto.setText("Aggiungi Contatto");
        aggiungiContatto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aggiungiContattoActionPerformed(evt);
            }
        });
        contattoMenu.add(aggiungiContatto);

        menuBar.add(contattoMenu);

        temiMenu.setText("Temi");

        chiaroItem.setText("Tema Chiaro");
        chiaroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chiaroItemActionPerformed(evt);
            }
        });
        temiMenu.add(chiaroItem);

        scuroItem.setText("Tema Scuro");
        scuroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scuroItemActionPerformed(evt);
            }
        });
        temiMenu.add(scuroItem);

        menuBar.add(temiMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cercaTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cercaTxtFocusGained
        if (cercaTxt.getText().equals("Cerca...")) {
            cercaTxt.setText("");
        }
    }//GEN-LAST:event_cercaTxtFocusGained

    private void cercaTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cercaTxtFocusLost
        if (cercaTxt.getText().isEmpty()) {
            cercaTxt.setText("Cerca...");
        }
    }//GEN-LAST:event_cercaTxtFocusLost

    private int rigaSelezionataPrecedente = -1;

    private void rubricaTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rubricaTblMouseClicked

        int rigaSelezionata = rubricaTbl.getSelectedRow();

        if (rigaSelezionata == rigaSelezionataPrecedente) {
            svuotaCampi();
            rubricaTbl.clearSelection();
            rigaSelezionataPrecedente = -1;

            System.out.println("Tolto");
        } else {
            trasportaDati();
            rigaSelezionataPrecedente = rigaSelezionata;

            System.out.println("Ho cliccato");
        }

    }//GEN-LAST:event_rubricaTblMouseClicked

    private void aggiungiContattoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aggiungiContattoActionPerformed
        controller = new ContattoController(this, model);
        controller.nuovoContatto();
    }//GEN-LAST:event_aggiungiContattoActionPerformed

    private void chiaroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chiaroItemActionPerformed
        try {
            // Imposta il tema Dark (FlatLaf)
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_chiaroItemActionPerformed

    private void scuroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scuroItemActionPerformed
        try {
            // Imposta il tema Dark (FlatLaf)
            UIManager.setLookAndFeel(new FlatDarkLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_scuroItemActionPerformed

    private void salvaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaItemActionPerformed
        if (model.isModified()) {
            controller.salvaSuFile();
            JOptionPane.showMessageDialog(null,
                    "Salvataggio Completato",
                    "Salvataggio",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Nessuna modifica da salvare.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_salvaItemActionPerformed

    private void addContattoFastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContattoFastBtnActionPerformed
        //Chiama il controller per la creazione di un nuovo contatto
        controller.nuovoContatto();
    }//GEN-LAST:event_addContattoFastBtnActionPerformed

    //codice quando si clicca il modificaaaaaa
    private void modificaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaBtnActionPerformed

        Contatto c = getContattoModificato();
        int riga = rubricaTbl.getSelectedRow();

        if (controller.modificaContatto(riga, c)) {
            modificaInTabella(c, riga);
        } else {
            JOptionPane.showMessageDialog(this, "Modifica non consentita", "Modifica", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_modificaBtnActionPerformed

    private void eliminaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaBtnActionPerformed

        int scelta = JOptionPane.showConfirmDialog(null,
                "Vuoi eliminare il contatto?",
                "Elimina Contatto",
                JOptionPane.YES_NO_OPTION);

        if (scelta == JOptionPane.YES_OPTION) {
            controller.eliminaContatto(nomeTxt.getText(), cognomeTxt.getText());
        }


    }//GEN-LAST:event_eliminaBtnActionPerformed

    private void salvaFastBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaFastBtnActionPerformed
        if (model.isModified()) {
            controller.salvaSuFile();
            JOptionPane.showMessageDialog(null,
                    "Salvataggio Completato",
                    "Salvataggio",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Nessuna modifica da salvare.",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_salvaFastBtnActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void cercaTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cercaTxtKeyReleased
        DefaultTableModel tbl = (DefaultTableModel) rubricaTbl.getModel();
        TableRowSorter<DefaultTableModel> riga = new TableRowSorter<>(tbl);
        rubricaTbl.setRowSorter(riga);
        riga.setRowFilter(RowFilter.regexFilter(cercaTxt.getText()));
        
    }//GEN-LAST:event_cercaTxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            // Usa FlatLightLaf per il tema chiaro
            UIManager.setLookAndFeel(new FlatLightLaf());
            // Per il tema scuro, usa FlatDarkLaf (come esempio)
            // UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contattoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addContattoFastBtn;
    private javax.swing.JMenuItem aggiungiContatto;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JPanel cercaPanel;
    private javax.swing.JTextField cercaTxt;
    private javax.swing.JMenuItem chiaroItem;
    private javax.swing.JLabel cognomeLbl;
    private javax.swing.JTextField cognomeTxt;
    private javax.swing.JLabel contattiPresLbl;
    private javax.swing.JMenu contattoMenu;
    private javax.swing.JPanel datiPanel;
    private javax.swing.JButton eliminaBtn;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JMenu fileMenu;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel mainModificaPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton modificaBtn;
    private javax.swing.JPanel modificaPanel;
    private javax.swing.JLabel nomeLbl;
    private javax.swing.JTextField nomeTxt;
    private javax.swing.JPanel ricercaBtnPanel;
    private javax.swing.JTable rubricaTbl;
    private javax.swing.JButton salvaFastBtn;
    private javax.swing.JMenuItem salvaItem;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JMenuItem scuroItem;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JLabel telefonoLbl;
    private javax.swing.JTextField telefonoTxt;
    private javax.swing.JMenu temiMenu;
    private javax.swing.JLabel titoloLbl;
    // End of variables declaration//GEN-END:variables

    public void aggiungiContattoTabella(Contatto c) { //Java Swing tutorial 11 - La tabella (1a parte)

        tableModel = (DefaultTableModel) rubricaTbl.getModel();
        tableModel.addRow(c.toArray());

    }

    public void modificaInTabella(Contatto c, int riga) {
        tableModel = (DefaultTableModel) rubricaTbl.getModel();

        tableModel.setValueAt(c.getNome(), riga, 0);
        tableModel.setValueAt(c.getCognome(), riga, 1);
        tableModel.setValueAt(c.getTelefono(), riga, 2);
        tableModel.setValueAt(c.getEmail(), riga, 3);

    }

    private void trasportaDati() {
        nomeTxt.setText(rubricaTbl.getModel().getValueAt(rubricaTbl.getSelectedRow(), 0).toString());
        cognomeTxt.setText(rubricaTbl.getModel().getValueAt(rubricaTbl.getSelectedRow(), 1).toString());
        telefonoTxt.setText(rubricaTbl.getModel().getValueAt(rubricaTbl.getSelectedRow(), 2).toString());
        emailTxt.setText(rubricaTbl.getModel().getValueAt(rubricaTbl.getSelectedRow(), 3).toString());

        nomeTxt.setEnabled(true);
        cognomeTxt.setEnabled(true);
        telefonoTxt.setEnabled(true);
        emailTxt.setEnabled(true);
        eliminaBtn.setEnabled(true);
        modificaBtn.setEnabled(true);

    }

// Funzione che svuota tutti i campi di testo
    private void svuotaCampi() {
        nomeTxt.setText("");
        cognomeTxt.setText("");
        telefonoTxt.setText("");
        emailTxt.setText("");

        nomeTxt.setEnabled(false);
        cognomeTxt.setEnabled(false);
        telefonoTxt.setEnabled(false);
        emailTxt.setEnabled(false);
        eliminaBtn.setEnabled(false);
        modificaBtn.setEnabled(false);
    }

    public void togliElementi() {

        tableModel = (DefaultTableModel) rubricaTbl.getModel();

        tableModel.removeRow(rubricaTbl.getSelectedRow());
        rubricaTbl.repaint();
        rubricaTbl.revalidate();
        rigaSelezionataPrecedente = -1;

        svuotaCampi();

    }

    private Contatto getContattoModificato() {
        Contatto contatto = new Contatto(nomeTxt.getText(), cognomeTxt.getText(), telefonoTxt.getText(), emailTxt.getText());

        return contatto;
    }

    public JLabel getContattiPresLbl() {
        return contattiPresLbl;
    }
    
    

}
